# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/cv_ov5640_axi_smc_0.xci
# IP: The module: 'cv_ov5640_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/bd_df34.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_0/bd_df34_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_1/bd_df34_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_2/bd_df34_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_3/bd_df34_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_4/bd_df34_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_5/bd_df34_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_6/bd_df34_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_7/bd_df34_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_8/bd_df34_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_9/bd_df34_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_10/bd_df34_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_11/bd_df34_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_12/bd_df34_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_13/bd_df34_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_14/bd_df34_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_15/bd_df34_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_16/bd_df34_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_17/bd_df34_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_18/bd_df34_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_19/bd_df34_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_20/bd_df34_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_21/bd_df34_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_22/bd_df34_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_23/bd_df34_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_24/bd_df34_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_25/bd_df34_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_26/bd_df34_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_27/bd_df34_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_28/bd_df34_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_29/bd_df34_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_30/bd_df34_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_31/bd_df34_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_32/bd_df34_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_33/bd_df34_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_34/bd_df34_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_35/bd_df34_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_36/bd_df34_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_37/bd_df34_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_38/bd_df34_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_39/bd_df34_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_1/bd_df34_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_1/bd_df34_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_2/bd_df34_arsw_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_3/bd_df34_rsw_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_4/bd_df34_awsw_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_5/bd_df34_wsw_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_6/bd_df34_bsw_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_10/bd_df34_s00a2s_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_11/bd_df34_sarn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_12/bd_df34_srn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_16/bd_df34_s01a2s_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_17/bd_df34_sawn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_18/bd_df34_swn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_19/bd_df34_sbn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_23/bd_df34_s02a2s_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_24/bd_df34_sarn_1_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_25/bd_df34_srn_1_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_29/bd_df34_s03a2s_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_30/bd_df34_sawn_1_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_31/bd_df34_swn_1_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_32/bd_df34_sbn_1_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_33/bd_df34_m00s2a_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_34/bd_df34_m00arn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_35/bd_df34_m00rn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_36/bd_df34_m00awn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_37/bd_df34_m00wn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_38/bd_df34_m00bn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cv_ov5640_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/cv_ov5640_axi_smc_0.xci
# IP: The module: 'cv_ov5640_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/bd_df34.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_0/bd_df34_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_1/bd_df34_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_2/bd_df34_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_3/bd_df34_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_4/bd_df34_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_5/bd_df34_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_6/bd_df34_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_7/bd_df34_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_8/bd_df34_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_9/bd_df34_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_10/bd_df34_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_11/bd_df34_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_12/bd_df34_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_13/bd_df34_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_14/bd_df34_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_15/bd_df34_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_16/bd_df34_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_17/bd_df34_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_18/bd_df34_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_19/bd_df34_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_20/bd_df34_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_21/bd_df34_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_22/bd_df34_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_23/bd_df34_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_24/bd_df34_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_25/bd_df34_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_26/bd_df34_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_27/bd_df34_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_28/bd_df34_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_29/bd_df34_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_30/bd_df34_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_31/bd_df34_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_32/bd_df34_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_33/bd_df34_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_34/bd_df34_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_35/bd_df34_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_36/bd_df34_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_37/bd_df34_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_38/bd_df34_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_39/bd_df34_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_1/bd_df34_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_1/bd_df34_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_2/bd_df34_arsw_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_3/bd_df34_rsw_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_4/bd_df34_awsw_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_5/bd_df34_wsw_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_6/bd_df34_bsw_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_10/bd_df34_s00a2s_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_11/bd_df34_sarn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_12/bd_df34_srn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_16/bd_df34_s01a2s_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_17/bd_df34_sawn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_18/bd_df34_swn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_19/bd_df34_sbn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_23/bd_df34_s02a2s_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_24/bd_df34_sarn_1_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_25/bd_df34_srn_1_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_29/bd_df34_s03a2s_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_30/bd_df34_sawn_1_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_31/bd_df34_swn_1_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_32/bd_df34_sbn_1_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_33/bd_df34_m00s2a_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_34/bd_df34_m00arn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_35/bd_df34_m00rn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_36/bd_df34_m00awn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_37/bd_df34_m00wn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_38/bd_df34_m00bn_0_ooc.xdc

# XDC: d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cv_ov5640_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
