# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.cache/wt [current_project]
set_property parent.project_path D:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths d:/Pynq_CV_OV5640_master/boards/src/ip [current_project]
update_ip_catalog
set_property ip_output_repo d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/hdl/cv_ov5640_wrapper.v
add_files D:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/cv_ov5640.bd
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_iic_0_0/cv_ov5640_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_iic_0_0/cv_ov5640_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_intc_0_0/cv_ov5640_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_intc_0_0/cv_ov5640_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_intc_0_0/cv_ov5640_axi_intc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_1/bd_df34_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_1/bd_df34_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_2/bd_df34_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_3/bd_df34_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_4/bd_df34_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_5/bd_df34_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_6/bd_df34_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_10/bd_df34_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_11/bd_df34_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_12/bd_df34_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_16/bd_df34_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_17/bd_df34_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_18/bd_df34_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_19/bd_df34_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_23/bd_df34_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_24/bd_df34_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_25/bd_df34_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_29/bd_df34_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_30/bd_df34_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_31/bd_df34_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_32/bd_df34_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_33/bd_df34_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_34/bd_df34_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_35/bd_df34_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_36/bd_df34_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_37/bd_df34_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/bd_0/ip/ip_38/bd_df34_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_vdma_0_0/cv_ov5640_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_vdma_0_0/cv_ov5640_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_vdma_0_0/cv_ov5640_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_vdma_1_0/cv_ov5640_axi_vdma_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_vdma_1_0/cv_ov5640_axi_vdma_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axi_vdma_1_0/cv_ov5640_axi_vdma_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_clk_wiz_0_0/cv_ov5640_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_clk_wiz_0_0/cv_ov5640_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_clk_wiz_0_0/cv_ov5640_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_xbar_0/cv_ov5640_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_0/cv_ov5640_auto_ss_slidr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_1/cv_ov5640_auto_ss_slidr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_2/cv_ov5640_auto_ss_slidr_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_3/cv_ov5640_auto_ss_slidr_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_4/cv_ov5640_auto_ss_slidr_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_5/cv_ov5640_auto_ss_slidr_5_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_6/cv_ov5640_auto_ss_slidr_6_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_ss_k_0/cv_ov5640_auto_ss_k_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_7/cv_ov5640_auto_ss_slidr_7_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_ss_k_1/cv_ov5640_auto_ss_k_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_8/cv_ov5640_auto_ss_slidr_8_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_xbar_1/cv_ov5640_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_ss_k_2/cv_ov5640_auto_ss_k_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_ss_slid_0/cv_ov5640_auto_ss_slid_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_ss_k_3/cv_ov5640_auto_ss_k_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_ss_slid_1/cv_ov5640_auto_ss_slid_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_9/cv_ov5640_auto_ss_slidr_9_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axis_subset_converter_0_0/cv_ov5640_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axis_subset_converter_1_0/cv_ov5640_axis_subset_converter_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axis_subset_converter_2_0/cv_ov5640_axis_subset_converter_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_axis_subset_converter_3_0/cv_ov5640_axis_subset_converter_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_canny_edge_0_0/constraints/canny_edge_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_equalizeHist_0_0/constraints/equalizeHist_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_gaussian_0_0/constraints/gaussian_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_rgb2hsv_0_0/constraints/rgb2hsv_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_sobelFilter_0_0/constraints/sobelFilter_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_subsample_0_0/constraints/subsample_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_xf_dilation_accel_0_0/constraints/xf_dilation_accel_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_xf_erosion_accel_0_0/constraints/xf_erosion_accel_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_processing_system7_0_0/cv_ov5640_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_xbar_2/cv_ov5640_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_pc_15/cv_ov5640_auto_pc_15_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_pc_0/cv_ov5640_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_pc_1/cv_ov5640_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_pc_2/cv_ov5640_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_pc_3/cv_ov5640_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_pc_4/cv_ov5640_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_pc_5/cv_ov5640_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_pc_6/cv_ov5640_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_pc_7/cv_ov5640_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_pc_8/cv_ov5640_auto_pc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_pc_9/cv_ov5640_auto_pc_9_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_pc_10/cv_ov5640_auto_pc_10_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_pc_11/cv_ov5640_auto_pc_11_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_pc_12/cv_ov5640_auto_pc_12_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_pc_13/cv_ov5640_auto_pc_13_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_auto_pc_14/cv_ov5640_auto_pc_14_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_rgb2dvi_0_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_rst_ps7_0_100M_0/cv_ov5640_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_rst_ps7_0_100M_0/cv_ov5640_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_rst_ps7_0_100M_0/cv_ov5640_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_v_axi4s_vid_out_0_0/cv_ov5640_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_v_axi4s_vid_out_0_0/cv_ov5640_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_v_demosaic_0_0/cv_ov5640_v_demosaic_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_v_demosaic_0_0/cv_ov5640_v_demosaic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_v_tc_0_0/cv_ov5640_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_v_tc_0_0/cv_ov5640_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_v_vid_in_axi4s_0_0/cv_ov5640_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/ip/cv_ov5640_v_vid_in_axi4s_0_0/cv_ov5640_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/sources_1/bd/cv_ov5640/cv_ov5640_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/constrs_1/imports/bitstream/cv_ov5640.xdc
set_property used_in_implementation false [get_files D:/Pynq_CV_OV5640_master/boards/Pynq_Z2/ov5640/bitstream/cv_ov5640/cv_ov5640.srcs/constrs_1/imports/bitstream/cv_ov5640.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top cv_ov5640_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cv_ov5640_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cv_ov5640_wrapper_utilization_synth.rpt -pb cv_ov5640_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
