# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/bitstream/cv_ov5640.xdc

# Block Designs: bd/cv_ov5640/cv_ov5640.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640 || ORIG_REF_NAME==cv_ov5640} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_axi_iic_0_0/cv_ov5640_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_axi_iic_0_0 || ORIG_REF_NAME==cv_ov5640_axi_iic_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_axi_intc_0_0/cv_ov5640_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_axi_intc_0_0 || ORIG_REF_NAME==cv_ov5640_axi_intc_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_axi_smc_0/cv_ov5640_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_axi_smc_0 || ORIG_REF_NAME==cv_ov5640_axi_smc_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_axi_vdma_0_0/cv_ov5640_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_axi_vdma_0_0 || ORIG_REF_NAME==cv_ov5640_axi_vdma_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_axi_vdma_1_0/cv_ov5640_axi_vdma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_axi_vdma_1_0 || ORIG_REF_NAME==cv_ov5640_axi_vdma_1_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_clk_wiz_0_0/cv_ov5640_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_clk_wiz_0_0 || ORIG_REF_NAME==cv_ov5640_clk_wiz_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_xbar_0/cv_ov5640_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_xbar_0 || ORIG_REF_NAME==cv_ov5640_xbar_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_0/cv_ov5640_auto_ss_slidr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_ss_slidr_0 || ORIG_REF_NAME==cv_ov5640_auto_ss_slidr_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_1/cv_ov5640_auto_ss_slidr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_ss_slidr_1 || ORIG_REF_NAME==cv_ov5640_auto_ss_slidr_1} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_2/cv_ov5640_auto_ss_slidr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_ss_slidr_2 || ORIG_REF_NAME==cv_ov5640_auto_ss_slidr_2} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_3/cv_ov5640_auto_ss_slidr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_ss_slidr_3 || ORIG_REF_NAME==cv_ov5640_auto_ss_slidr_3} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_4/cv_ov5640_auto_ss_slidr_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_ss_slidr_4 || ORIG_REF_NAME==cv_ov5640_auto_ss_slidr_4} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_5/cv_ov5640_auto_ss_slidr_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_ss_slidr_5 || ORIG_REF_NAME==cv_ov5640_auto_ss_slidr_5} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_6/cv_ov5640_auto_ss_slidr_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_ss_slidr_6 || ORIG_REF_NAME==cv_ov5640_auto_ss_slidr_6} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_ss_k_0/cv_ov5640_auto_ss_k_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_ss_k_0 || ORIG_REF_NAME==cv_ov5640_auto_ss_k_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_7/cv_ov5640_auto_ss_slidr_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_ss_slidr_7 || ORIG_REF_NAME==cv_ov5640_auto_ss_slidr_7} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_ss_k_1/cv_ov5640_auto_ss_k_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_ss_k_1 || ORIG_REF_NAME==cv_ov5640_auto_ss_k_1} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_8/cv_ov5640_auto_ss_slidr_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_ss_slidr_8 || ORIG_REF_NAME==cv_ov5640_auto_ss_slidr_8} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_axis_interconnect_0_0/cv_ov5640_axis_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_axis_interconnect_0_0 || ORIG_REF_NAME==cv_ov5640_axis_interconnect_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_xbar_1/cv_ov5640_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_xbar_1 || ORIG_REF_NAME==cv_ov5640_xbar_1} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_ss_k_2/cv_ov5640_auto_ss_k_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_ss_k_2 || ORIG_REF_NAME==cv_ov5640_auto_ss_k_2} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_ss_slid_0/cv_ov5640_auto_ss_slid_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_ss_slid_0 || ORIG_REF_NAME==cv_ov5640_auto_ss_slid_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_ss_k_3/cv_ov5640_auto_ss_k_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_ss_k_3 || ORIG_REF_NAME==cv_ov5640_auto_ss_k_3} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_ss_slid_1/cv_ov5640_auto_ss_slid_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_ss_slid_1 || ORIG_REF_NAME==cv_ov5640_auto_ss_slid_1} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_ss_slidr_9/cv_ov5640_auto_ss_slidr_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_ss_slidr_9 || ORIG_REF_NAME==cv_ov5640_auto_ss_slidr_9} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_axis_interconnect_1_0/cv_ov5640_axis_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_axis_interconnect_1_0 || ORIG_REF_NAME==cv_ov5640_axis_interconnect_1_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_axis_subset_converter_0_0/cv_ov5640_axis_subset_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_axis_subset_converter_0_0 || ORIG_REF_NAME==cv_ov5640_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_axis_subset_converter_1_0/cv_ov5640_axis_subset_converter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_axis_subset_converter_1_0 || ORIG_REF_NAME==cv_ov5640_axis_subset_converter_1_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_axis_subset_converter_2_0/cv_ov5640_axis_subset_converter_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_axis_subset_converter_2_0 || ORIG_REF_NAME==cv_ov5640_axis_subset_converter_2_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_axis_subset_converter_3_0/cv_ov5640_axis_subset_converter_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_axis_subset_converter_3_0 || ORIG_REF_NAME==cv_ov5640_axis_subset_converter_3_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_canny_edge_0_0/cv_ov5640_canny_edge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_canny_edge_0_0 || ORIG_REF_NAME==cv_ov5640_canny_edge_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_equalizeHist_0_0/cv_ov5640_equalizeHist_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_equalizeHist_0_0 || ORIG_REF_NAME==cv_ov5640_equalizeHist_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_gaussian_0_0/cv_ov5640_gaussian_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_gaussian_0_0 || ORIG_REF_NAME==cv_ov5640_gaussian_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_rgb2hsv_0_0/cv_ov5640_rgb2hsv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_rgb2hsv_0_0 || ORIG_REF_NAME==cv_ov5640_rgb2hsv_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_sobelFilter_0_0/cv_ov5640_sobelFilter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_sobelFilter_0_0 || ORIG_REF_NAME==cv_ov5640_sobelFilter_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_subsample_0_0/cv_ov5640_subsample_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_subsample_0_0 || ORIG_REF_NAME==cv_ov5640_subsample_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_xf_dilation_accel_0_0/cv_ov5640_xf_dilation_accel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_xf_dilation_accel_0_0 || ORIG_REF_NAME==cv_ov5640_xf_dilation_accel_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_xf_erosion_accel_0_0/cv_ov5640_xf_erosion_accel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_xf_erosion_accel_0_0 || ORIG_REF_NAME==cv_ov5640_xf_erosion_accel_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_xlconstant_2_0/cv_ov5640_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_xlconstant_2_0 || ORIG_REF_NAME==cv_ov5640_xlconstant_2_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_processing_system7_0_0/cv_ov5640_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_processing_system7_0_0 || ORIG_REF_NAME==cv_ov5640_processing_system7_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_xbar_2/cv_ov5640_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_xbar_2 || ORIG_REF_NAME==cv_ov5640_xbar_2} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_pc_15/cv_ov5640_auto_pc_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_pc_15 || ORIG_REF_NAME==cv_ov5640_auto_pc_15} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_pc_0/cv_ov5640_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_pc_0 || ORIG_REF_NAME==cv_ov5640_auto_pc_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_pc_1/cv_ov5640_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_pc_1 || ORIG_REF_NAME==cv_ov5640_auto_pc_1} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_pc_2/cv_ov5640_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_pc_2 || ORIG_REF_NAME==cv_ov5640_auto_pc_2} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_pc_3/cv_ov5640_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_pc_3 || ORIG_REF_NAME==cv_ov5640_auto_pc_3} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_pc_4/cv_ov5640_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_pc_4 || ORIG_REF_NAME==cv_ov5640_auto_pc_4} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_pc_5/cv_ov5640_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_pc_5 || ORIG_REF_NAME==cv_ov5640_auto_pc_5} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_pc_6/cv_ov5640_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_pc_6 || ORIG_REF_NAME==cv_ov5640_auto_pc_6} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_pc_7/cv_ov5640_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_pc_7 || ORIG_REF_NAME==cv_ov5640_auto_pc_7} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_pc_8/cv_ov5640_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_pc_8 || ORIG_REF_NAME==cv_ov5640_auto_pc_8} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_pc_9/cv_ov5640_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_pc_9 || ORIG_REF_NAME==cv_ov5640_auto_pc_9} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_pc_10/cv_ov5640_auto_pc_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_pc_10 || ORIG_REF_NAME==cv_ov5640_auto_pc_10} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_pc_11/cv_ov5640_auto_pc_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_pc_11 || ORIG_REF_NAME==cv_ov5640_auto_pc_11} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_pc_12/cv_ov5640_auto_pc_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_pc_12 || ORIG_REF_NAME==cv_ov5640_auto_pc_12} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_pc_13/cv_ov5640_auto_pc_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_pc_13 || ORIG_REF_NAME==cv_ov5640_auto_pc_13} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_auto_pc_14/cv_ov5640_auto_pc_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_auto_pc_14 || ORIG_REF_NAME==cv_ov5640_auto_pc_14} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_ps7_0_axi_periph_0/cv_ov5640_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_ps7_0_axi_periph_0 || ORIG_REF_NAME==cv_ov5640_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_rgb2dvi_0_0/cv_ov5640_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_rgb2dvi_0_0 || ORIG_REF_NAME==cv_ov5640_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_rst_ps7_0_100M_0/cv_ov5640_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_rst_ps7_0_100M_0 || ORIG_REF_NAME==cv_ov5640_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_v_axi4s_vid_out_0_0/cv_ov5640_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==cv_ov5640_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_v_demosaic_0_0/cv_ov5640_v_demosaic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_v_demosaic_0_0 || ORIG_REF_NAME==cv_ov5640_v_demosaic_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_v_tc_0_0/cv_ov5640_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_v_tc_0_0 || ORIG_REF_NAME==cv_ov5640_v_tc_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_v_vid_in_axi4s_0_0/cv_ov5640_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==cv_ov5640_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_xlconcat_0_0/cv_ov5640_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_xlconcat_0_0 || ORIG_REF_NAME==cv_ov5640_xlconcat_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_xlconstant_0_0/cv_ov5640_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_xlconstant_0_0 || ORIG_REF_NAME==cv_ov5640_xlconstant_0_0} -quiet] -quiet

# IP: bd/cv_ov5640/ip/cv_ov5640_xlconstant_1_0/cv_ov5640_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cv_ov5640_xlconstant_1_0 || ORIG_REF_NAME==cv_ov5640_xlconstant_1_0} -quiet] -quiet

# XDC: bd/cv_ov5640/cv_ov5640_ooc.xdc
